// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYnGqgMdVEbjDrVjGoMbkflLPTHvBY1wY',
    appId: '1:210957965133:web:1d7a1471231e1137860904',
    messagingSenderId: '210957965133',
    projectId: 'wsa-new',
    authDomain: 'wsa-new.firebaseapp.com',
    storageBucket: 'wsa-new.firebasestorage.app',
    measurementId: 'G-RTW8E07RLC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxY_ge5YwiE1zkmo9sLlQhT6oeSw7VZto',
    appId: '1:210957965133:android:0d27ba9f5149294f860904',
    messagingSenderId: '210957965133',
    projectId: 'wsa-new',
    storageBucket: 'wsa-new.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_YbVPMJOm96ZLOSoCWab4wcVyOBP_2QA',
    appId: '1:210957965133:ios:4775f649262b61c1860904',
    messagingSenderId: '210957965133',
    projectId: 'wsa-new',
    storageBucket: 'wsa-new.firebasestorage.app',
    iosBundleId: 'com.example.wsaNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_YbVPMJOm96ZLOSoCWab4wcVyOBP_2QA',
    appId: '1:210957965133:ios:4775f649262b61c1860904',
    messagingSenderId: '210957965133',
    projectId: 'wsa-new',
    storageBucket: 'wsa-new.firebasestorage.app',
    iosBundleId: 'com.example.wsaNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYnGqgMdVEbjDrVjGoMbkflLPTHvBY1wY',
    appId: '1:210957965133:web:0f152e2955a8656c860904',
    messagingSenderId: '210957965133',
    projectId: 'wsa-new',
    authDomain: 'wsa-new.firebaseapp.com',
    storageBucket: 'wsa-new.firebasestorage.app',
    measurementId: 'G-R0D9KRNT8M',
  );
}
